<?php

/**
 * Implementation of hook_permission().
 */
function mockup_permission() {
  $permissions = array();

  $permissions['administer mockups'] = array(
    'title' => t('Administer mockups'),
    'description' => t('Administer mockups.'),
    'restrict access' => TRUE,
  );

  return $permissions;
}

/**
 * Implementation of hook_menu().
 */
function mockup_menu() {
  $module_path = drupal_get_path('module', 'mockup');
  $module_includes_path = "{$module_path}/includes";

  $items = array();

  $items['admin/structure/mockups'] = array(
    'title' => 'Mockups',
    'description' => 'Manage mockups.',
    'page callback' => 'mockup_list',
    'access arguments' => array('administer mockups'),
    'file' => 'mockup.admin.inc',
    'file path' => $module_includes_path,
  );

  return $items;
}

/**
 * Implementation of hook_process_html().
 */
function mockup_process_html(&$variables) {
  $module_path = drupal_get_path('module', 'mockup');
  $module_js_path = "{$module_path}/js";

  $require_js = array(
    '#tag' => 'script',
    '#attributes' => array(
      'data-main' => "/{$module_js_path}/main.js",
      'src' => "/{$module_js_path}/libraries/require/require.js",
    ),
  );

  $variables['scripts'] .=
    "<script data-main=\"/{$module_js_path}/main\" " .
      "src=\"/{$module_js_path}/libraries/require/require.js\"></script>";
}
