<?php

/**
 * Implementation of hook_permission().
 */
function mockup_permission() {
  $permissions = array();

  $permissions['administer mockups'] = array(
    'title' => t('Administer mockups'),
    'description' => t('Administer mockups.'),
    'restrict access' => TRUE,
  );

  return $permissions;
}

/**
 * Implementation of hook_menu().
 */
function mockup_menu() {
  $items = array();

  $items['admin/structure/mockups'] = array(
    'title' => 'Mockups',
    'description' => 'Manage mockups.',
    'page callback' => 'mockup_list',
    'access arguments' => array('administer mockups'),
  );

  return $items;
}
