<?php

/**
 * Implementation of hook_permission().
 */
function mockups_permission() {
  $permissions = array();

  $permissions['administer mockups'] = array(
    'title' => t('Administer mockups'),
    'description' => t('Administer mockups.'),
    'restrict access' => TRUE,
  );

  return $permissions;
}

/**
 * Implementation of hook_menu().
 */
function mockups_menu() {
  $module_path = drupal_get_path('module', 'mockups');
  $module_includes_path = "{$module_path}/includes";

  $items = array();

  $items['admin/structure/mockups'] = array(
    'title' => 'Mockups',
    'description' => 'Manage mockups.',
    'page callback' => 'mockups_list',
    'access arguments' => array('administer mockups'),
    'file' => 'mockups.admin.inc',
    'file path' => $module_includes_path,
  );

  return $items;
}

/**
 * Implementation of hook_preprocess_html_tag().
 */
function mockups_preprocess_html_tag(&$variables) {
  if (isset($variables['element']['#attributes']['src'])) {
    $attributes =& $variables['element']['#attributes'];

    $module_js_path = base_path() . drupal_get_path('module', 'mockups') . '/js';
    $pattern = "#{$module_js_path}/libraries/require/require\.js#";

    if (preg_match($pattern, $attributes['src'])) {
      $attributes['data-main'] = "{$module_js_path}/main";
    }
  }
}
